### ISSUE TITLE
Request a default port for the chai-exporter

### ISSUE THREAD

**Issue by sbates130272** [speedmann/prometheus-chia-exporter#3]
The port used for chia_exporter is currently 8000 which I do not think is a safe port. Instead update the default Prometheus port wiki to allocate a new port for this exporter and then update the port used by the exporter.

https://github.com/prometheus/prometheus/wiki/Default-port-allocations

**Comment by speedmann** [comment]
Fixed in d11fed2596940db815e24bf45f40f4e511e2dbab

**Comment by sbates130272** [comment]
Thanks @speedmann!
