### ISSUE TITLE
"self_hostname" referenced but not used?

### ISSUE THREAD

**Issue by sbates130272** [speedmann/prometheus-chia-exporter#5]
The README.md mentions a "self_hostname" in the exporter but this string is not in the exporter? Am I missing something?

Also, "sudo not sudp" in one spot in the README.

**Comment by speedmann** [comment]
Yes you are right, it was removed when introducing the `override hostname` feature
Are you running the exporter on the same system as you are running the node/farmer?

**Comment by speedmann** [comment]
I will implement a better way to set the hostnames when running as a systemd service

**Comment by speedmann** [comment]
A new version is now up. Feedback would be appreciated

**Comment by sbates130272** [comment]
@speedmann your change looks good and works for me. I like the env file approach. Can I ask you are more verbose and descriptive in your commit messages please? Useful in the long term....

**Comment by speedmann** [comment]
Yes i will try to be more descriptive in the next commits
